//
//  AuthBackendContract.swift
//  transium
//

import Foundation

protocol AuthBackend: Sendable {
    // Verify Apple sign-in and create an app session.
    func verifyAppleSignIn(_ credential: AppleSignInCredential) async throws -> AuthSession

    // Authenticated user operations.
    func fetchPrivateProfile(accessToken: String) async throws -> BackendProfile
    func upsertPrivateProfile(_ profile: BackendProfile, accessToken: String) async throws -> BackendProfile
    func signOut(accessToken: String) async throws
}

nonisolated struct AuthSession: Codable, Equatable, Sendable {
    let userID: String
    let accessToken: String
    let profile: BackendProfile
}

nonisolated struct BackendProfile: Codable, Identifiable, Equatable, Sendable {
    // User ID generated by Better Auth.
    let id: String
    var firstName: String
    var lastName: String?
    var method: String
    var level: String

    init(
        id: String,
        firstName: String,
        lastName: String? = nil,
        method: String = AuthMethod.apple.rawValue,
        level: String = ProfileLevel.standard.rawValue
    ) {
        self.id = id
        self.firstName = firstName
        self.lastName = lastName
        self.method = method
        self.level = level
    }
}

nonisolated enum BackendError: Error, LocalizedError, Sendable {
    case invalidResponse
    case unauthorized(String?)
    case requestFailed(status: Int, message: String?)
    case missingSessionToken
    case unsupported(String)

    var errorDescription: String? {
        switch self {
        case .invalidResponse:
            "The server sent a response the app could not read."
        case let .unauthorized(message):
            message ?? "This session is no longer valid. Please sign in again."
        case let .requestFailed(status, message):
            message ?? "The server returned an unexpected error (\(status))."
        case .missingSessionToken:
            "The server did not return a session token."
        case let .unsupported(message):
            message
        }
    }
}

nonisolated enum AuthBackendRequirement: String, Codable, CaseIterable, Sendable {
    case verifyAppleNonce
    case keepRefreshTokenServerSideOnly
    case requireAuthenticatedUserForProfileRoutes
    case enforceProfileOwnerAccess
    case sanitizeProfileNames
}
